// import agents images
import Agent1 from './assets/img/agents/agent1.png';
import Agent2 from './assets/img/agents/agent2.png';
import Agent3 from './assets/img/agents/agent3.png';

export const housesData = [
  {
    id: 1,
    type: 'House',
    name: 'House 1',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273373/Real-Estate/Houses/mzxofo3cmrkzxtdq48tp.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266887/Real-Estate/Houses/eyrskaisnjm0kny3emqj.png",
    country: 'United States',
    address: '7240C Argyle St. Lawndale, CA 90260',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2016',
    price: '110,000',
    agent: {
      image: Agent1,
      name: 'Patricia Tullert',
      phone: '0123 456 78910',
    },
  },
  {
    id: 2,
    type: 'House',
    name: 'House 2',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273502/Real-Estate/Houses/rb9bogsl9tmu4geo1u7y.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266935/Real-Estate/Houses/mwareepwcvqbyvqalg3a.png",
    country: 'Canada',
    address: '798 Talbot St. Bridgewater, NJ 08807',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2016',
    price: '140,000',
    agent: {
      image: Agent2,
      name: 'Daryl Hawker',
      phone: '0123 456 78910',
    },
  },
  {
    id: 3,
    type: 'House',
    name: 'House 3',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273553/Real-Estate/Houses/cqwxishyirve1zxm4yft.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266985/Real-Estate/Houses/nnrpldm6ht5cmvpwpbdv.png",
    country: 'Nigeria',
    address: '51B, Okepopo Street, Lagos Island, Lagos',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2016',
    price: '170,000',
    agent: {
      image: Agent3,
      name: 'AdeKunle Opeyemi',
      phone: '0123 456 78910',
    },
  },
  {
    id: 4,
    type: 'House',
    name: 'House 4',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273604/Real-Estate/Houses/c5kssjakruysseax2sux.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267032/Real-Estate/Houses/xwnqhdar0n1gjgtm8i9x.png",
    country: 'Canada',
    address: '84 Woodland St. Cocoa, FL 32927',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2016',
    price: '200,000',
    agent: {
      image: Agent1,
      name: 'Kaitlyn Gonzalez',
      phone: '0123 456 78910',
    },
  },
  {
    id: 5,
    type: 'House',
    name: 'House 5',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273657/Real-Estate/Houses/ebenaqlkyrv9ttpd4xzv.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267079/Real-Estate/Houses/argan5kvliygfapwcv0w.png",
    country: 'United States',
    address: '28 Westport Dr. Warminster, PA 18974',
    bedrooms: '5',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2015',
    price: '210,000',
    agent: {
      image: Agent2,
      name: 'Grover Robinson',
      phone: '0123 456 78910',
    },
  },
  {
    id: 6,
    type: 'House',
    name: 'House 6',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273709/Real-Estate/Houses/n88frjgqqogfrowsxb5k.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267121/Real-Estate/Houses/vuzvaypfkb789exqikkg.png",
    country: 'Canada',
    address: '32 Pawnee Street Butte, MT 59701',
    bedrooms: '6',
    bathrooms: '3',
    surface: '6200 sq ft',
    year: '2014',
    price: '220,000',
    agent: {
      image: Agent3,
      name: 'Karen Sorensen',
      phone: '0123 456 78910',
    },
  },
  {
    id: 7,
    type: 'Apartment',
    name: 'Apartment 1',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274017/Real-Estate/Apartments/gndp4nmqywnwgl0a1azm.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266001/Real-Estate/Apartments/bulbnhhpwx7ef53fcqip.png",
    country: 'Nigeria',
    address: '17 Oremet Street, Ikeja, Lagos',
    bedrooms: '2',
    bathrooms: '1',
    surface: '1200 sq ft',
    year: '2012',
    price: '20,000',
    agent: {
      image: Agent3,
      name: 'Orimadegun Hameedah',
      phone: '0123 456 78910',
    },
  },
  {
    id: 8,
    type: 'Apartment',
    name: 'Apartment 2',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274064/Real-Estate/Apartments/frre0dcseipntjayk6l8.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266088/Real-Estate/Apartments/iqw2l74rdxzsvts2rz3g.png",
    country: 'United States',
    address: '28 Westport Dr. Warminster, PA 18974',
    bedrooms: '3',
    bathrooms: '1',
    surface: '1000 sq ft',
    year: '2011',
    price: '30,000',
    agent: {
      image: Agent2,
      name: 'Juana Douglass',
      phone: '0123 456 78910',
    },
  },
  {
    id: 9,
    type: 'Apartment',
    name: 'Apartment 3',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274100/Real-Estate/Apartments/cicyamrdca1t8edhcphz.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266128/Real-Estate/Apartments/wsqbygxmmqdslf3d2m5k.png",
    country: 'United States',
    address: '84 Woodland St. Cocoa, FL 32927',
    bedrooms: '2',
    bathrooms: '1',
    surface: '1100 sq ft',
    year: '2011',
    price: '40,000',
    agent: {
      image: Agent1,
      name: 'Jerry Schenck',
      phone: '0123 456 78910',
    },
  },
  {
    id: 10,
    type: 'House',
    name: 'House 7',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273750/Real-Estate/Houses/my94gy5speqfnqgbugnb.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267183/Real-Estate/Houses/daox7qj1rcjunuubuztf.png",
    country: 'Canada',
    address: '7240C Argyle St. Lawndale, CA 90260',
    bedrooms: '5',
    bathrooms: '3',
    surface: '3200 sq ft',
    year: '2015',
    price: '117,000',
    agent: {
      image: Agent2,
      name: 'Vera Levesque',
      phone: '0123 456 78910',
    },
  },
  {
    id: 11,
    type: 'House',
    name: 'House 8',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273790/Real-Estate/Houses/zuc5086gjxkt1wri4c1p.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267230/Real-Estate/Houses/zqumsccb9coh0ahxj4jn.png",
    country: 'Canada',
    address: '798 Talbot St. Bridgewater, NJ 08807',
    bedrooms: '7',
    bathrooms: '2',
    surface: '2200 sq ft',
    year: '2019',
    price: '145,000',
    agent: {
      image: Agent3,
      name: 'Sofia Gomes',
      phone: '0123 456 78910',
    },
  },
  {
    id: 12,
    type: 'House',
    name: 'House 9',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273832/Real-Estate/Houses/srhq2qgd2ggvnajyjuki.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267282/Real-Estate/Houses/cuetqtp2qukcgozwy7ri.png",
    country: 'Nigeria',
    address: '24B, Pike Street, Lagos Island, Lagos',
    bedrooms: '4',
    bathrooms: '4',
    surface: '4600 sq ft',
    year: '2015',
    price: '139,000',
    agent: {
      image: Agent1,
      name: 'Emmanuel Charles',
      phone: '0123 456 78910',
    },
  },
  {
    id: 13,
    type: 'House',
    name: 'House 10',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273868/Real-Estate/Houses/w9zg8bvjejspz4w3wtjo.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267328/Real-Estate/Houses/hen2ezv2ksrlnjd219qi.png",
    country: 'Canada',
    address: '84 Woodland St. Cocoa, FL 32927',
    bedrooms: '5',
    bathrooms: '2',
    surface: '5200 sq ft',
    year: '2014',
    price: '180,000',
    agent: {
      image: Agent2,
      name: 'Patricia Tullert',
      phone: '0123 456 78910',
    },
  },
  {
    id: 14,
    type: 'House',
    name: 'House 11',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273909/Real-Estate/Houses/s3sgfn22askfghk21nbz.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267380/Real-Estate/Houses/btemtb7v82unm2cdi6yd.png",
    country: 'United States',
    address: '28 Westport Dr. Warminster, PA 18974',
    bedrooms: '5',
    bathrooms: '2',
    surface: '3200 sq ft',
    year: '2011',
    price: '213,000',
    agent: {
      image: Agent3,
      name: 'Daryl Hawker',
      phone: '0123 456 78910',
    },
  },
  {
    id: 15,
    type: 'House',
    name: 'House 12',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684273958/Real-Estate/Houses/kx9sncu2tz5yxrd8flji.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267425/Real-Estate/Houses/sgyujuhjt2akqrofvtb7.png",
    country: 'Canada',
    address: '32 Pawnee Street Butte, MT 59701',
    bedrooms: '4',
    bathrooms: '3',
    surface: '5200 sq ft',
    year: '2013',
    price: '221,000',
    agent: {
      image: Agent3,
      name: 'Amado Smith',
      phone: '0123 456 78910',
    },
  },
  {
    id: 16,
    type: 'Virgin Land',
    name: 'VirginLand1',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274316/Real-Estate/Apartments/cu0nrxkcp4qt6e3nugye.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267689/Real-Estate/Apartments/tvdjtvlxrh6hnivppskf.png",
    country: 'Canada',
    address: '32 Pawnee Street Butte, MT 59701',
    // bedrooms: '2',
    // bathrooms: '1',
    // surface: '1300 sq ft',
    year: '2011',
    price: '21,000',
    agent: {
      image: Agent2,
      name: 'Kaitlyn Gonzalez',
      phone: '0123 456 78910',
    },
  },
  {
    id: 17,
    type: 'Apartment',
    name: 'Apartment 17',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274144/Real-Estate/Apartments/tdsskumpbdm2ffzhsyd0.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266160/Real-Estate/Apartments/orioypeypwilt9xiymdb.png",
    country: 'Canada',
    address: '32 Pawnee Street Butte, MT 59701',
    bedrooms: '2',
    bathrooms: '1',
    surface: '1300 sq ft',
    year: '2011',
    price: '21,000',
    agent: {
      image: Agent3,
      name: 'Kaitlyn Gonzalez',
      phone: '0123 456 78910',
    },
  },
  {
    id: 18,
    type: 'Apartment',
    name: 'Apartment 18',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274174/Real-Estate/Apartments/l6zgi4lfap3i4svwvl8c.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266194/Real-Estate/Apartments/jyvtrdd9ehxalurtmcaa.png",
    country: 'United States',
    address: '28 Westport Dr. Warminster, PA 18974',
    bedrooms: '3',
    bathrooms: '1',
    surface: '1000 sq ft',
    year: '2012',
    price: '32,000',
    agent: {
      image: Agent1,
      name: 'Grover Robinson',
      phone: '0123 456 78910',
    },
  },
  {
    id: 19,
    type: 'Virgin Land',
    name: 'VirginLand2',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274423/Real-Estate/Apartments/uwpwyoh6whnekndkoccm.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267759/Real-Estate/Apartments/fqn6wh1enhtqv1cqaozg.jpg",
    country: 'Nigeria',
    address: '84 Woodland St. Cocoa, FL 32927',
    // bedrooms: '3',
    // bathrooms: '1',
    // surface: '1200 sq ft',
    year: '2010',
    price: '38,000',
    agent: {
      image: Agent2,
      name: 'Karen Sorensen',
      phone: '0123 456 78910',
    },
  },
  {
    id: 20,
    type: 'Apartment',
    name: 'Apartment 19',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274228/Real-Estate/Apartments/y258tntl87zuqjuzfczo.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684266231/Real-Estate/Apartments/hjwfoe8oynsdmwsxydyc.png",
    country: 'Canada',
    address: '84 Woodland St. Cocoa, FL 32927',
    bedrooms: '3',
    bathrooms: '1',
    surface: '1200 sq ft',
    year: '2010',
    price: '38,000',
    agent: {
      image: Agent1,
      name: 'Karen Sorensen',
      phone: '0123 456 78910',
    },
  },
  {
    id: 21,
    type: 'Virgin Land',
    name: 'VirginLand3',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
    image: "https://res.cloudinary.com/hameedah-images/image/upload/v1684274510/Real-Estate/Apartments/gtkmnv2evnauetrzniv1.png",
    imageLg: "https://res.cloudinary.com/hameedah-images/image/upload/v1684267731/Real-Estate/Apartments/hvjcftjgnsifengoxp9b.jpg",
    country: 'Canada',
    address: '84 Woodland St. Cocoa, FL 32927',
    // bedrooms: '3',
    // bathrooms: '1',
    // surface: '1200 sq ft',
    year: '2010',
    price: '38,000',
    agent: {
      image: Agent2,
      name: 'Karen Sorensen',
      phone: '0123 456 78910',
    },
  }, 
];
